"""Static HTML dashboard generated from the paper-account state.

Produces a single self-contained page (plus Chart.js from a CDN) suitable
for GitHub Pages or any static host. Contains only simulated-account data —
there is nothing sensitive in it by construction.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from paperbot.backtest.metrics import max_drawdown, sharpe_ratio
from paperbot.config import Config
from paperbot.paper.state import PaperState

_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>crypto-paperbot — paper trading dashboard</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js"></script>
<style>
  :root { color-scheme: dark; }
  * { box-sizing: border-box; margin: 0; }
  body { font-family: -apple-system, "Segoe UI", Roboto, sans-serif;
         background: #0d1117; color: #e6edf3; padding: 24px; max-width: 1000px;
         margin: 0 auto; }
  .banner { background: #3d2c00; border: 1px solid #9e6a03; color: #f0c674;
            padding: 10px 14px; border-radius: 8px; margin-bottom: 20px;
            font-size: 14px; }
  .halted { background: #4c1414; border-color: #da3633; color: #ff7b72;
            font-weight: 600; }
  h1 { font-size: 22px; margin-bottom: 4px; }
  .sub { color: #8b949e; font-size: 13px; margin-bottom: 20px; }
  .cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
           gap: 12px; margin-bottom: 24px; }
  .card { background: #161b22; border: 1px solid #30363d; border-radius: 10px;
          padding: 14px; }
  .card .label { color: #8b949e; font-size: 12px; text-transform: uppercase;
                 letter-spacing: 0.04em; }
  .card .value { font-size: 22px; font-weight: 650; margin-top: 4px; }
  .pos { color: #3fb950; } .neg { color: #f85149; }
  .chart-wrap { background: #161b22; border: 1px solid #30363d; border-radius: 10px;
                padding: 16px; margin-bottom: 24px; }
  h2 { font-size: 15px; margin: 22px 0 10px; color: #c9d1d9; }
  table { width: 100%; border-collapse: collapse; font-size: 13px;
          background: #161b22; border: 1px solid #30363d; border-radius: 10px;
          overflow: hidden; }
  th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid #21262d; }
  th { color: #8b949e; font-weight: 500; background: #0d1117; }
  tr:last-child td { border-bottom: none; }
  .num { text-align: right; font-variant-numeric: tabular-nums; }
  .empty { color: #8b949e; padding: 14px; font-size: 13px; }
  footer { color: #8b949e; font-size: 12px; margin-top: 28px; line-height: 1.6; }
</style>
</head>
<body>
<div class="banner">🧪 <strong>Paper money.</strong> This is a simulation with a
virtual $__START__ account. No real orders are ever placed. Costs are modeled
pessimistically (0.26% taker fee + 0.05% slippage per fill).</div>
__HALTED_BANNER__
<h1>crypto-paperbot</h1>
<div class="sub">BTC/USDT &amp; ETH/USDT · 1h candles · strategies: trendfollow, meanrevert ·
last updated __UPDATED__ UTC</div>

<div class="cards">
  <div class="card"><div class="label">Equity</div>
    <div class="value">$__EQUITY__</div></div>
  <div class="card"><div class="label">Total return</div>
    <div class="value __RET_CLS__">__RETURN__%</div></div>
  <div class="card"><div class="label">Drawdown from peak</div>
    <div class="value">__DD__%</div></div>
  <div class="card"><div class="label">Max drawdown</div>
    <div class="value">__MAXDD__%</div></div>
  <div class="card"><div class="label">Closed trades</div>
    <div class="value">__NTRADES__</div></div>
  <div class="card"><div class="label">Win rate</div>
    <div class="value">__WINRATE__</div></div>
</div>

<div class="chart-wrap"><canvas id="eq" height="90"></canvas></div>

<h2>Open positions</h2>
__POSITIONS__

<h2>Recent trades</h2>
__TRADES__

<footer>
Generated by <strong>crypto-paperbot</strong>, an event-driven paper-trading
simulator. Fills happen at the next bar's open, stops are checked intrabar and
assumed to beat take-profits, and every fill pays worst-tier taker fees plus
slippage. Honest disclosure: in walk-forward validation over 2022–2026, both
bundled strategies <em>lost to buy-and-hold after costs</em>. This dashboard
exists to observe that honestly, not to sell a strategy. Paper results
overstate live results (flat slippage, no latency, no partial fills,
survivor-pair selection, overfitting risk).
</footer>

<script>
const pts = __CURVE__;
new Chart(document.getElementById("eq"), {
  type: "line",
  data: { labels: pts.map(p => p[0]), datasets: [{
    label: "equity ($)", data: pts.map(p => p[1]),
    borderColor: "#58a6ff", backgroundColor: "rgba(88,166,255,0.12)",
    fill: true, pointRadius: 0, borderWidth: 1.6, tension: 0.15 }] },
  options: {
    plugins: { legend: { display: false } },
    interaction: { mode: "index", intersect: false },
    scales: {
      x: { ticks: { color: "#8b949e", maxTicksLimit: 8 }, grid: { color: "#21262d" } },
      y: { ticks: { color: "#8b949e", callback: v => "$" + v.toLocaleString() },
           grid: { color: "#21262d" } }
    }
  }
});
</script>
</body>
</html>
"""


def _fmt_ts(ms: int) -> str:
    return datetime.fromtimestamp(ms / 1000, tz=timezone.utc).strftime("%Y-%m-%d %H:%M")


def _table(headers: list[str], rows: list[list[str]], numeric_cols: set[int]) -> str:
    if not rows:
        return '<div class="empty">none yet</div>'
    head = "".join(f"<th>{h}</th>" for h in headers)
    body = ""
    for row in rows:
        cells = "".join(
            f'<td class="num">{c}</td>' if i in numeric_cols else f"<td>{c}</td>"
            for i, c in enumerate(row)
        )
        body += f"<tr>{cells}</tr>"
    return f"<table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table>"


def build_dashboard(cfg: Config, out_dir: Path) -> Path:
    """Render the dashboard to `out_dir`/index.html and return the path."""
    state = PaperState(cfg.paper.state_db)
    try:
        account, _pending = state.load_account(cfg.paper.starting_balance)
        curve = state.equity_curve()
        start = cfg.paper.starting_balance

        if curve.empty:
            equity, ret, dd, maxdd = account.cash, 0.0, 0.0, 0.0
            points: list[list[object]] = [[datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M"), start]]
        else:
            equity = float(curve.iloc[-1])
            ret = 100 * (equity / start - 1.0)
            dd = 100 * (1.0 - equity / account.peak_equity) if account.peak_equity else 0.0
            maxdd = 100 * max_drawdown(curve)
            # Downsample to <= 600 points so the page stays light.
            step = max(1, len(curve) // 600)
            sampled = curve.iloc[::step]
            if sampled.index[-1] != curve.index[-1]:
                import pandas as pd

                sampled = pd.concat([sampled, curve.iloc[[-1]]])
            points = [
                [ts.strftime("%Y-%m-%d %H:%M"), round(float(v), 2)]
                for ts, v in sampled.items()
            ]

        wins = [t for t in account.trades if t.pnl > 0]
        winrate = f"{100 * len(wins) / len(account.trades):.0f}%" if account.trades else "—"

        pos_rows = []
        for pos in account.positions.values():
            pos_rows.append([
                pos.symbol, pos.strategy, f"{pos.qty:.6f}",
                f"${pos.entry_price:,.2f}", f"${pos.stop_price:,.2f}",
                _fmt_ts(pos.entry_ts),
            ])

        trade_rows = []
        for t in state.recent_trades(20):
            cls = "pos" if t.pnl > 0 else "neg"
            trade_rows.append([
                _fmt_ts(t.exit_ts), t.symbol, t.strategy,
                f'<span class="{cls}">{t.pnl:+,.2f}</span>',
                f"{t.fees:,.2f}", t.exit_reason,
            ])

        halted_banner = (
            '<div class="banner halted">⛔ KILL SWITCH FIRED — equity fell 15% from '
            "its peak. The account is flattened and halted.</div>"
            if account.halted else ""
        )

        html = (
            _TEMPLATE
            .replace("__START__", f"{start:,.0f}")
            .replace("__HALTED_BANNER__", halted_banner)
            .replace("__UPDATED__", datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M"))
            .replace("__EQUITY__", f"{equity:,.2f}")
            .replace("__RET_CLS__", "pos" if ret >= 0 else "neg")
            .replace("__RETURN__", f"{ret:+.2f}")
            .replace("__DD__", f"{dd:.1f}")
            .replace("__MAXDD__", f"{maxdd:.2f}")
            .replace("__NTRADES__", str(len(account.trades)))
            .replace("__WINRATE__", winrate)
            .replace("__POSITIONS__", _table(
                ["symbol", "strategy", "qty", "entry", "stop", "opened (UTC)"],
                pos_rows, {2, 3, 4}))
            .replace("__TRADES__", _table(
                ["closed (UTC)", "symbol", "strategy", "pnl ($)", "fees ($)", "reason"],
                trade_rows, {3, 4}))
            .replace("__CURVE__", json.dumps(points))
        )
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / "index.html"
        out_path.write_text(html)
        return out_path
    finally:
        state.close()
